"""add embeddings and near-duplicate link

Revision ID: a3e869ddad19
Revises: 33dd27b3a0d7
Create Date: 2026-09-28 17:52:05.819166

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3e869ddad19'
down_revision: Union[str, Sequence[str], None] = '33dd27b3a0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Needed on fresh databases (e.g. a hosted Postgres); docker/init.sql does this locally.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('jobs', sa.Column('embedded_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('jobs', sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_jobs_duplicate_of_id'), 'jobs', ['duplicate_of_id'], unique=False)
    op.create_foreign_key('jobs_duplicate_of_id_fkey', 'jobs', 'jobs', ['duplicate_of_id'], ['id'])
    op.add_column('profiles', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'embedding')
    op.drop_constraint('jobs_duplicate_of_id_fkey', 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_duplicate_of_id'), table_name='jobs')
    op.drop_column('jobs', 'duplicate_of_id')
    op.drop_column('jobs', 'embedded_hash')
    op.drop_column('jobs', 'embedding')
    # ### end Alembic commands ###
